databaseType = "MariaDb"
id = "ca4c9651-fa99-4347-b499-a4ad6cc3e96c"
name = "Flyway"

[flyway]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
validateMigrationNaming = true

  [flyway.check]
  majorTolerance = 0

[flywayDesktop]
developmentEnvironment = "development"
schemaModel = "schema-model"
shadowEnvironment = "shadow"

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.1]
url = "jdbc:mysql://localhost:3306"
schemas = [ "flyway.user=root flyway.password=mypassword" ]
